artifacts:
- path: build\pkg
  name: CouchExplorerArtifacts

before_build:
  - ps: gitversion $env:APPVEYOR_BUILD_FOLDER /l console /output buildserver /updateAssemblyInfo /nofetch /b $env:APPVEYOR_REPO_BRANCH

branches:
  only:
    - develop
    - master
    - /release/.*/

build_script:
  - ps: ./build -t Full

cache:
  - tools -> build.cake

image: Visual Studio 2017

skip_branch_with_pr: true

test: off

version: '{build}'
